### ISSUE TITLE
field meta_robots not available

### ISSUE THREAD

**Issue by fzadow** [saintybalboa/nutchmetarobots#1]
Hi saintybalboa!
When I try to use your IndexingFilter, the `meta_robots` field does not exist in the Document(s) I crawled (i.e. `document.getFieldValue("meta_robots");` is NULL). Do you happen to know how I have to adjust the crawling to make sure `meta_robots` is in the document?
Many thanks!

**Comment by saintybalboa** [comment]
Hi fzadow,

You need to specify 'parse-metatags' and 'index-metadata' plugins within nutch-site.xml:

```
<property>
    <name>plugin.includes</name>
    <value>nutchmetarobots|scoring-opic|protocol-(http|https)|urlfilter-regex|parse-(html|metatags|tika)|urlnormalizer-(pass|basic|regex)|index-(basic|metadata|more|static)|indexer-solr</value>
</property>
```

You also need to specify the robots metatag field for the index metadata plugin:

```
  <property>
    <name>index.metadata</name>
    <!-- Comma delimetered list of meta tags -->
    <value>robots</value>
  </property>
```

Hope this helps.

**Comment by fzadow** [comment]
Thank you for the clarification. Now the plugin works!
